stages:
  - build
  - beta

cache:
  key:
    files:
      - Gemfile.lock
  paths:
    - vendor/bundle

.macos_saas_runners:
  tags:
    - saas-macos-medium-m1
  image: macos-12-xcode-14

build_ios_rosetta:
  extends:
    - .macos_saas_runners
  stage: build
  before_script:
    - echo "Is Rosetta 2 installed?"
    - /usr/bin/pgrep -q oahd && echo Yes || echo No
    - /usr/sbin/softwareupdate --install-rosetta --agree-to-license
    - echo "Is Rosetta 2 installed?"
    - /usr/bin/pgrep -q oahd && echo Yes || echo No
    - echo "Installing Homebrew for x86_64"
    - arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - eval "$(/usr/local/bin/brew shellenv)" 
    - export PATH="/usr/local/bin:/usr/local/sbin:/Users/gitlab/.asdf/shims:/Users/gitlab/.asdf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin"
    - echo "Installing Ruby via Homebrew"
    - arch -x86_64 brew install ruby
    - export PATH="/usr/local/opt/ruby/bin:$PATH"
  script:
    - arch -x86_64 bundle install
    - arch -x86_64 bundle exec fastlane build

build_ios:
  extends:
    - .macos_saas_runners
  stage: build
  script:
    - bundle check --path vendor/bundle || bundle install --path vendor/bundle --jobs $(nproc)
    - bundle exec fastlane build

beta_ios:
  extends:
    - .macos_saas_runners
  stage: beta
  script:
    - bundle check --path vendor/bundle || bundle install --path vendor/bundle --jobs $(nproc)
    - bundle exec fastlane beta
  when: manual
  allow_failure: true
  only:
    refs:
      - main
