stages:
  - build
  - beta

cache:
  key:
    files:
      - Gemfile.lock
  paths:
    - vendor/bundle

.build_ios:
  image: macos-14-xcode-15
  stage: build
  script:
    - bundle check --path vendor/bundle || bundle install --path vendor/bundle --jobs $(nproc)
    - bundle exec fastlane build
  parallel: 30

build_ios_m1:
  extends: .build_ios
  tags: 
    - saas-macos-medium-m1
  parallel: 10

build_ios_m2pro:
  extends: .build_ios
  tags: 
    - saas-macos-large-m2pro

.beta_ios:
  image: macos-14-xcode-15
  stage: beta
  script:
    - bundle check --path vendor/bundle || bundle install --path vendor/bundle --jobs $(nproc)
    - bundle exec fastlane beta
  allow_failure: true

beta_ios_m1:
  extends: .beta_ios
  tags: 
    - saas-macos-medium-m1

beta_ios_m2pro:
  extends: .beta_ios
  tags: 
    - saas-macos-large-m2pro