stages:
  - build
  - beta

build_ios:
  stage: build
  script:
    - source ~/.bashrc
    - bundle install
    - bundle exec fastlane build
  tags: 
    - macbook-air-m1

beta_ios:
  stage: beta
  script:
    - source ~/.bashrc
    - bundle install
    - bundle exec fastlane beta
  tags: 
    - macbook-air-m1
  when: manual
  allow_failure: true
  only:
    refs:
      - main
