lane :build_for_simulator do
  build_app(
    scheme: "ios demo",
    configuration: "Debug",
    sdk: "iphonesimulator",
    export_method: nil,
    destination: "generic/platform=iOS Simulator",
    skip_package_ipa: true,
    skip_archive: true,
    build_path: "build"
)
end
