default_platform(:ios)

platform :ios do
  desc "Build and sign the application for development"
  lane :build do
    # Detect if we are running in CI, and create a temporary keychain
    # and switch match to readonly mode
    # https://docs.fastlane.tools/actions/setup_ci/
    setup_ci

    # Download and install the correct signing certificates for the 
    # given build environment, in this case development
    # https://docs.fastlane.tools/actions/match/
    match(type: 'development', readonly: is_ci)

    # Build the app with the supplied configuration settings
    # Export method is the same as the match step above
    # https://docs.fastlane.tools/actions/build_app/
    build_app(
      project: "ios demo.xcodeproj",
      scheme: "ios demo",
      configuration: "Debug",
      export_method: "development"
    )
  end

  desc "Build and sign the application for distribution, upload to TestFlight"
  lane :beta do
    # Detect if we are running in CI, and create a temporary keychain
    # and switch match to readonly mode
    # https://docs.fastlane.tools/actions/setup_ci/
    setup_ci

    # Download and install the correct signing certificates for the 
    # given build environment, in this case appstore
    # https://docs.fastlane.tools/actions/match/
    match(type: 'appstore', readonly: is_ci)

    # Login to App Store Connect in order to perform actions later
    # in this process. Configuration provided by environment variables added
    # by the GitLab Apple Apps Store integration 
    # https://docs.gitlab.com/ee/user/project/integrations/apple_app_store.html
    # https://docs.fastlane.tools/actions/app_store_connect_api_key/
    app_store_connect_api_key(
      is_key_content_base64: true
    )

    # Auto increment the build number for Test Flight
    # https://docs.fastlane.tools/actions/increment_build_number/
    # https://docs.fastlane.tools/actions/latest_testflight_build_number/
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "ios demo.xcodeproj"
    )

    # Build the app with the supplied configuration settings
    # Export method is the same as the match step above
    # Note: the difference between `appstore` and `app-store` is intentional
    # https://docs.fastlane.tools/actions/build_app/
    build_app(
      project: "ios demo.xcodeproj",
      scheme: "ios demo",
      configuration: "Release",
      export_method: "app-store"
    )

    # Upload the newly created build to Test Flight using the App Store Connect
    # API key above, and the app configuration in the Appfile
    # https://docs.fastlane.tools/actions/upload_to_testflight/
    upload_to_testflight
  end
end

