
name: iOS Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Install Fastlane
        run: gem install fastlane
        # generate the signing certificates and provisioning profiles for our app
      
      - name: Run Build
        run: |
          xcodebuild -scheme "ios demo" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO build archive -archivePath ${{ github.workspace }}/ios_demo.xcarchive -destination 'generic/platform=iOS'  

          ls /Users/runner/Library/Developer/Xcode/DerivedData/ios_demo-cmuzcbcjvxsekzadiatuzsfbfxvx/Build/Products/Debug-iphonesimulator/
          xcodebuild -scheme "ios demo" -showBuildSettings | grep BUILD_DIR
        if: always()
      - name: List build directory
        run: |
          echo "present working : $pwd"
          ls /Users/runner/Library/Developer/Xcode/DerivedData/ios_demo-cmuzcbcjvxsekzadiatuzsfbfxvx/Build/Products/Debug-iphoneos
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: "${{ github.workspace }}/ios_demo.xcarchive"
  deploy:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ${{ github.workspace }}

      - name: Compress the .app file
        run: |
          ls -lrt Products
          cd Products/Applications
          ls -ltr
          
          cd ${{ github.workspace }}/Products/Applications
          zip -r ios_demo.zip "ios demo.app"

      - name: Upload to Appetize
        run: |
          curl --http1.1 https://tok_uqegreafft5ppbyfpzw22cuxlm@api.appetize.io/v1/apps -F "file=@${{ github.workspace }}/Products/Applications/ios_demo.zip" -F "platform=ios"
          #curl -v -F "file=@${{ github.workspace }}/Products/Applications/ios_demo.zip" -H "Authorization: Bearer tok_uqegreafft5ppbyfpzw22cuxlm" https://appetize.io/upload
      
