name: iOS Build and Deploy 

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: snyk scanning
        #https://docs.snyk.io/snyk-cli/install-or-update-the-snyk-cli
        run : |
          brew tap snyk/tap
          brew install snyk
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Run Snyk Test
        run: snyk test --severity-threshold=medium --sarif-file-output=snyk_report.sarif || true
      - name: Upload Snyk Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: |
             snyk_report.sarif

      - name: Run SwiftLint
        run: |
          brew install swiftlint
          swiftlint version
          swiftlint lint --reporter html > swiftlint_report.html || true
      - name: Upload SwiftLint Report
        uses: actions/upload-artifact@v4
        with:
          name: swiftlint-report
          path: |
             swiftlint_report.html
      - name: Install Gitleaks
        run: brew install gitleaks  # For macOS
         
      - name: Run Gitleaks
        env:
          GITLEAKS_ENABLE_SUMMARY: true
        run: |
          gitleaks detect --source .  --report-format json --report-path gitleaks-report.json --verbose || true
          
          echo "### Gitleaks scan Report" >> $GITHUB_STEP_SUMMARY
          jq '.' gitleaks-report.json >> $GITHUB_STEP_SUMMARY
        
        
        
      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
        if: always()
      - name: Install SonarScanner CLI
        run: |
        
          curl -OL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.0.2.4839-macosx-x64.zip
          unzip sonar-scanner-cli-7.0.2.4839-macosx-x64.zip
          export PATH=$PATH:$(pwd)/sonar-scanner-7.0.2.4839-macosx-x64/bin
          echo "PATH: $PATH"
          echo "SonarScanner path: $(which sonar-scanner)"
          sonar-scanner --version  
      - name: SonarCloud Scan
        run: |
          echo "Current working directory: $(pwd)"
          export JAVA_HOME=$JAVA_HOME
          export PATH=$JAVA_HOME/bin:$PATH
          echo "testing java home: $JAVA_HOME"
          $(pwd)/sonar-scanner-7.0.2.4839-macosx-x64/bin/sonar-scanner \
            -Dsonar.projectKey=tishapuri_demo \
            -Dsonar.organization=iosdemo \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      #- name: unit test 
      #run: |
          #echo "running unit test"
          #xcodebuild test -scheme "ios demo" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro Max'
      - name: Build the app
        run: |
          xcrun simctl list devices
          xcodebuild -scheme "ios demo" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro Max' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO build -derivedDataPath $GITHUB_WORKSPACE/target
          xcodebuild -scheme "ios demo" -showBuildSettings | grep BUILD_DIR
          xcodebuild -scheme "ios demo" -configuration Debug -sdk iphonesimulator -showBuildSettings | grep BUILD_DIR
         
        if: always()
        
      - name: List build directory
        run: |
          echo "present working : $(pwd)"
          echo "workspace directory is $GITHUB_WORKSPACE" 
          ls -ltr $GITHUB_WORKSPACE/target/Build/Products/Debug-iphonesimulator
          

      - name: Compress the .app file
        run: |
          echo "present working : $(pwd)"
          cd  $GITHUB_WORKSPACE/target/Build/Products/Debug-iphonesimulator
          ls -ltr
          zip -r ios_demo.zip "ios demo.app"

      - name: Upload to Appetize
        run: |
          curl --http1.1 https://${{ secrets.APPETIZE_TOKEN }}@api.appetize.io/v1/apps -F "file=@$GITHUB_WORKSPACE/target/Build/Products/Debug-iphonesimulator/ios_demo.zip" -F "platform=ios"
          
