
name: iOS Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Install Fastlane
        run: gem install fastlane
        # generate the signing certificates and provisioning profiles for our app
      
      - name: Run SwiftLint
        run: |
          brew install swiftlint
          swiftlint version
          swiftlint lint --reporter html > swiftlint_report.html || true
      - name: Upload SwiftLint Report
        uses: actions/upload-artifact@v4
        with:
          name: swiftlint-report
          path: |
             swiftlint_report.html
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install SonarScanner CLI
        run: |
          curl -OL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-macosx.zip
          unzip sonar-scanner-cli-4.6.2.2472-macosx.zip
          export PATH=$PATH:$(pwd)/sonar-scanner-4.6.2.2472-macosx/bin
          
      - name: Verify SonarScanner Installation
        run: |
          echo "Current working directory: $(pwd)"
          echo "SonarScanner path: $(which sonar-scanner)"
          sonar-scanner --version 
          
      - name: SonarCloud using Scan
        run: |
          echo "Current working directory: $(pwd)"
          sonar-scanner \
            -Dsonar.projectKey=iosdemo \
            -Dsonar.organization=tishapuri \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=1eccb394e2d052b41b04c5c4fb8890f44fd6ad7a
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: 1eccb394e2d052b41b04c5c4fb8890f44fd6ad7a
          SONAR_PROJECT_KEY: iosdemo
          SONAR_ORGANIZATION: tishapuri
          SONAR_HOST_URL: https://sonarcloud.io
          
      - name: Run tests
        run: |  
          xcrun simctl list
          xcodebuild -list -project "ios demo.xcodeproj"
          xcodebuild test -scheme "ios demo" -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest' -only-testing:"ios demoTests"| xcpretty
        if: always()
