
name: iOS Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Install Fastlane
        run: gem install fastlane
        # generate the signing certificates and provisioning profiles for our app
      
      - name: Run Build
        run: |
          xcodebuild -scheme "ios demo" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO build -archivePath /Users/runner/Library/Developer/Xcode/DerivedData/ios_demo-cmuzcbcjvxsekzadiatuzsfbfxvx/Build/Products/Debug-iphoneos/ios_demo.xcarchive
          find /Users/runner/Library/Developer/Xcode/DerivedData/ios_demo-cmuzcbcjvxsekzadiatuzsfbfxvx/Build/Products -name "*.app"
          ls /Users/runner/Library/Developer/Xcode/DerivedData/ios_demo-cmuzcbcjvxsekzadiatuzsfbfxvx/Build/Products/Debug-iphoneos/
        run: xcodebuild -scheme "ios demo" -showBuildSettings | grep BUILD_DIR
        if: always()
      - name: List build directory
        run: |
          echo "present working : $pwd"
          ls /Users/runner/Library/Developer/Xcode/DerivedData/ios_demo-cmuzcbcjvxsekzadiatuzsfbfxvx/Build/Products/Debug-iphoneos
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: "/Users/runner/Library/Developer/Xcode/DerivedData/ios_demo-cmuzcbcjvxsekzadiatuzsfbfxvx/Build/Products/Debug-iphoneos/ios_demo.xcarchive"
      - name: Run tests
        run: |  
          xcrun simctl list
          xcodebuild -list -project "ios demo.xcodeproj"
          xcodebuild test -scheme "ios demo" -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest' -only-testing:"ios demoTests"| xcpretty
  
