
name: iOS Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Install Fastlane
        run: gem install fastlane
        # generate the signing certificates and provisioning profiles for our app
      
      - name: Compile the build 
        run: |
          xcrun simctl list devices
          xcodebuild -scheme "ios demo" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro Max' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO build 
          ls /Users/runner/Library/Developer/Xcode/DerivedData/ios_demo-cmuzcbcjvxsekzadiatuzsfbfxvx/Build/Products/Debug-iphoneos/
          ls /Users/runner/Library/Developer/Xcode/DerivedData/ios_demo-cmuzcbcjvxsekzadiatuzsfbfxvx/Build/Products/Debug-iphonesimulator
          xcodebuild -scheme "ios demo" -showBuildSettings | grep BUILD_DIR
        if: always()
      - name: List build directory
        run: |
          echo "present working : $pwd"
          ls /Users/runner/Library/Developer/Xcode/DerivedData/ios_demo-cmuzcbcjvxsekzadiatuzsfbfxvx/Build/Products/Debug-iphonesimulator
    

      - name: Compress the .app file
        run: |
          #ls -lrt Products
          #cd /Users/runner/Library/Developer/Xcode/DerivedData/ios_demo-cmuzcbcjvxsekzadiatuzsfbfxvx/Build/Products/Debug-iphoneos/
          cd  /Users/runner/Library/Developer/Xcode/DerivedData/ios_demo-cmuzcbcjvxsekzadiatuzsfbfxvx/Build/Products/Debug-iphonesimulator
          ls -ltr
          xcrun simctl boot "iPhone 15 Pro Max"
          xcrun simctl install booted "ios demo.app"
          echo "running simulator..wait"
          #cd ${{ github.workspace }}/Products/Applications
          zip -r ios_demo.zip "ios demo.app"

      - name: Upload to Appetize
        run: |
          curl --http1.1 https://tok_uqegreafft5ppbyfpzw22cuxlm@api.appetize.io/v1/apps -F "file=@/Users/runner/Library/Developer/Xcode/DerivedData/ios_demo-cmuzcbcjvxsekzadiatuzsfbfxvx/Build/Products/Debug-iphoneos/ios_demo.zip" -F "platform=ios"
          #curl -v -F "file=@${{ github.workspace }}/Products/Applications/ios_demo.zip" -H "Authorization: Bearer tok_uqegreafft5ppbyfpzw22cuxlm" https://appetize.io/upload
      
