
name: iOS Build and Deploy 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Install Fastlane
        run: gem install fastlane
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
           languages: ['swift']  # Adjust languages as needed
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        
      - name: Run SwiftLint
        run: |
          brew install swiftlint
          swiftlint version
          swiftlint lint --reporter html > swiftlint_report.html || true
      - name: Upload SwiftLint Report
        uses: actions/upload-artifact@v4
        with:
          name: swiftlint-report
          path: |
             swiftlint_report.html
      - name: Install Gitleaks
        run: brew install gitleaks  # For macOS
         # For Windows, you might need to use a different installation method

      - name: Run Gitleaks
        env:
          GITLEAKS_ENABLE_SUMMARY: true
        run: |
          gitleaks detect --source .  --report-format json --report-path gitleaks-report.json --verbose || true
          
          echo "### Gitleaks scan Report" >> $GITHUB_STEP_SUMMARY
          jq '.' gitleaks-report.json >> $GITHUB_STEP_SUMMARY
        
        
        
      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
        if: always()
        
      - name: Build the app
        run: |
          xcrun simctl list devices
          xcodebuild -scheme "ios demo" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro Max' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO build -derivedDataPath $GITHUB_WORKSPACE/target
          xcodebuild -scheme "ios demo" -showBuildSettings | grep BUILD_DIR
          xcodebuild -scheme "ios demo" -configuration Debug -sdk iphonesimulator -showBuildSettings | grep BUILD_DIR
         
        if: always()
        
      - name: List build directory
        run: |
          echo "present working : $(pwd)"
          echo "workspace directory is $GITHUB_WORKSPACE" 
          ls -ltr $GITHUB_WORKSPACE/target/Build/Products/Debug-iphonesimulator
          

      - name: Compress the .app file
        run: |
          echo "present working : $(pwd)"
          cd  $GITHUB_WORKSPACE/target/Build/Products/Debug-iphonesimulator
          ls -ltr
          #xcrun simctl boot "iPhone 15 Pro Max"
          #xcrun simctl install booted "ios demo.app"
          #echo "running simulator..wait"
          #xcrun simctl launch booted com.gitlab.ios-demo
          zip -r ios_demo.zip "ios demo.app"

      - name: Upload to Appetize
        run: |
          #curl --http1.1 https://tok_uqegreafft5ppbyfpzw22cuxlm@api.appetize.io/v1/apps -F "file=@$GITHUB_WORKSPACE/target/Build/Products/Debug-iphonesimulator/ios_demo.zip" -F "platform=ios"
          
