name: MS Teams Notification

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # this is the new step using the ms-teams-notification action
      - name: Notify dedicated teams channel
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          ms-teams-webhook-uri: https://cvcmail.webhook.office.com/webhookb2/42535c46-f01f-4dd0-87bc-e6a8b715684a@cf535dc0-73fc-41ea-a174-17f37ced7fe7/IncomingWebhook/ebfb076d3b5d4a7eba7abd86eb28ff6a/ce6333b6-df44-4e45-b8c3-6e36b1896589/V2H1s2PhKPQUhyFfjgUNr9eedvvvRW_q1ulpxIsulrnsE1
          notification-summary: Deployment started
          notification-color: 17a2b8
          timezone: America/Denver
          verbose-logging: true
